services:
  # Contenedor 1: La Base de Datos
  db:
    image: postgres:15-alpine
    container_name: nombre_contenedor
    environment:
      POSTGRES_USER: nombre_usuario_base_creado
      POSTGRES_PASSWORD: contraseña # Pon tu contraseña real aquí
      POSTGRES_DB: nombre_base
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Contenedor 2: Tu API
  fastapi_app:
    build: .
    container_name: andesmarket_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped